# Generated by Django 5.1.4 on 2024-12-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
