# Generated by Django 5.1.4 on 2024-12-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
