# Generated by Django 5.1.4 on 2024-12-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
